import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Global/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Netflix Clone",
  description: "Netflix Clone Generated by Eren Tin",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
