import { Inter } from "next/font/google";
import '@/app/globals.css'
import { Clerk, ClerkProvider } from "@clerk/nextjs";

import Header from "@/components/Global/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Netflix Clone",
  description: "Netflix Clone Generated by Eren Tin",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
 

      <html lang="en">
        <body className={inter.className}>
          
          {children}
        </body>
      </html>

    </ClerkProvider>
  );
}
